version: "3.9"
services:
################## 01 #######################
  openvpn-1:
    image: free32com/openvpn-nc
    cap_drop:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "4001:1080"
    environment:
      - IP_SERVER=msy-c26.vpn.wlvpn.com
  
  p2p-1:
    image: free32com/ubuntu-p2p:1.1
    environment:
      - MAIL=xiaomi.blackshark04@gmail.com
      - IP_PORT=4001
    network_mode: "host"
